### ISSUE TITLE
I have an error with elevenlabs.

### ISSUE THREAD

**Issue by ghost** [clevaway/J.A.R.V.I.S#16]
PS C:\Users\...\J.A.R.V.I.S-main\J.A.R.V.I.S-main> python main.py
Traceback (most recent call last):
  File "C:\Users\...\J.A.R.V.I.S-main\J.A.R.V.I.S-main\main.py", line 8, in <module>
    from modules.Interlocus import Interlocus
  File "C:\Users\...\J.A.R.V.I.S-main\J.A.R.V.I.S-main\modules\Interlocus.py", line 5, in <module>
    from elevenlabs import generate, play
ImportError: cannot import name 'generate' from 'elevenlabs' (C:\Users\...\elevenlabs\__init__.py)

**Comment by FotieMConstant** [comment]
yeah, sorry about that, you have to create an elevenlabs account and link you api key accordingly. with the voice as well

ps: we plan to eliminate that in the future and have a full offline tts.

**Comment by Itseliganee** [comment]
I took an api key but it didn't work aswell

**Comment by FotieMConstant** [comment]
these are things i ought to have added in the `.env` file to make things easier, just keep forgetting. apologies for the inconvenience

**Comment by Itseliganee** [comment]
im gonna search for the error

**Comment by VinayakGhai** [comment]
nah man it's still not working, can you please make a detailed tutorial description on it?

**Comment by VinayakGhai** [comment]
like in a way that how would you set it up on your pc..

**Comment by FotieMConstant** [comment]
> nah man it's still not working, can you please make a detailed tutorial description on it?

you should check the code and add the voice id from elevenlabs, use any for now

**Comment by FotieMConstant** [comment]
this PR should fix the issue, check the `.env.example` file in root

**Comment by AmanGamer** [comment]
Traceback (most recent call last):
  File "c:\Users\..\JARVIS\main.py", line 8, in <module>
    from modules.Interlocus import Interlocus
  File "c:\Users\..\JARVIS\modules\Interlocus.py", line 5, in <module>
    from elevenlabs import generate
ImportError: cannot import name 'generate' from 'elevenlabs' (C:\Users\..\elevenlabs\__init__.py)

**Comment by FotieMConstant** [comment]
Hey guys, apologies for the wait. this error has now been addressed and resolved in PR #20, tts should now be working perfectly, 100% locally.

thanks.
