### ISSUE TITLE
ApiError: status_code: 401, body: {'detail': {'status': 'needs_authorization'

### ISSUE THREAD

**Issue by muleskin** [clevaway/J.A.R.V.I.S#18]
Here's the full error. This is returned when trying to TTS from elevenlabs. 

Traceback (most recent call last):
  File "C:\Users\Jedd\PycharmProjects\J.A.R.V.I.S\main.py", line 157, in <module>
    main()
  File "C:\Users\Jedd\PycharmProjects\J.A.R.V.I.S\main.py", line 153, in main
    interlocus.speak(processed_input)
  File "C:\Users\Jedd\PycharmProjects\J.A.R.V.I.S\modules\Interlocus.py", line 23, in speak
    audio = generate(
            ^^^^^^^^^
  File "C:\Users\Jedd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\elevenlabs\generate.py", line 57, in generate
    return TTS.generate(text, voice, model, api_key=api_key)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jedd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\elevenlabs\tts.py", line 54, in generate
    return bytes(b"".join(response))
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jedd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\elevenlabs\resources\text_to_speech\client.py", line 87, in convert
    raise ApiError(status_code=_response.status_code, body=_response_json)
elevenlabs.core.api_error.ApiError: status_code: 401, body: {'detail': {'status': 'needs_authorization', 'message': 'Neither authorization header nor xi-api-key received, please provide one.'}}

Contents of my .env file

ELEVEN_API_KEY='sk_<removed for security reasons>'
# JARVIS_MODEL='jarvis:latest' # for local dev and testing of model before pushing to hub
JARVIS_MODEL='fotiecodes/jarvis:latest' # for usage: uncomment and use this instead if you downloaded model from https://ollama.com/fotiecodes/jarvis
VISION_MODEL='llava'
ELEVENLABS_VOICE_ID='Xr<removed for security reasons>

**Comment by FotieMConstant** [comment]
Hi, this error has been addressed and resolved in PR #20, tts should now be working perfectly, 100% locally.

thanks.
